template_dir: "templates"
output_dir: "terraform"
tfstate_file: "terraform.tfstate"
state_file: "existing_resources.json"
default_repository:
  visibility: "private"
  description: "Default repository"
  gitignore_template: "None"
default_team:
  privacy: "closed"
  role: "member"
  description: "Default team"
default_membership:
  role: "member"
default_repository_collaborator:
  permission: "pull"